name: $(Date:yyyyMMdd)$(Rev:.r)

#resources:
#  repositories:
#  - repository: vue # The name used to reference this repository in the checkout step
#    type: github
#    endpoint: stampin-up
#    name: vue-components
    
trigger: none

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  name: 'Docker Build'

stages:
- stage: 'Configure_git'
  displayName: 'Configure git'
  jobs:
  - job: Git
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
      lfs: false
      submodules: false
      persistCredentials: true

    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
      displayName: 'Use Yarn 1.x'

    - task: Cache@2
      displayName: 'Yarn Cache'
      inputs:
        key: 'yarn | "$(Agent.OS) | yarn.lock'
        path: $(YARN_CACHE_FOLDER)
        cacheHitVar: 'YARN_CACHE_HIT'
      enabled: true
  
    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
      displayName: 'Yarn Install'
      inputs:
        Arguments: install --frozen-lockfile

#    - task: Bash@3
#      displayName: 'git checkout master'
#      inputs:
#        targetType: 'inline'
#        script: 'git checkout master'
# we need to login to the npm registry before we try to push.  example code npm-cli-login -u Username -p Password -e test@example.com -r https://your-private-registry-link
    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
      displayName: 'Yarn Publish'
      inputs:
        Arguments: release    

