name: $(Date:yyyyMMdd)$(Rev:.r)

#resources:
#  repositories:
#  - repository: vue # The name used to reference this repository in the checkout step
#    type: github
#    endpoint: stampin-up
#    name: vue-components
    
trigger: none

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  name: 'Docker Build'

stages:
- stage: 'Configure_git'
  displayName: 'Configure git'
  jobs:
  - job: Git
    steps:
    - checkout: self
      persistCredentials: true

#    - task: Bash@3
#      displayName: 'git checkout branch'
#      inputs:
#        targetType: 'inline'
#        script: 'git checkout bffoust'

#    - task: Bash@3
#      displayName: 'ssh-add'
#      inputs:
#        targetType: 'inline'
#        script: 'eval `ssh-agent -s` && echo "$SSH_AUTH_SOCK" && ssh-add'

#    - task: Bash@3
#      displayName: 'git config --global --add url.git@github.com:.insteadOf https://github.com/'
#      inputs:
#        targetType: 'inline'
#        script: 'git config --global --add url."git@github.com:".insteadOf "https://github.com/"'

    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
      displayName: 'Use Yarn 1.x'

    - task: Cache@2
      displayName: 'Yarn Cache'
      inputs:
        key: 'yarn | "$(Agent.OS) | yarn.lock'
        path: $(YARN_CACHE_FOLDER)
        cacheHitVar: 'YARN_CACHE_HIT'
      enabled: true
  
    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
      displayName: 'Yarn Install'
      inputs:
        Arguments: install --frozen-lockfile

    - task: Bash@3
      displayName: 'git checkout master'
      inputs:
        targetType: 'inline'
        script: 'git checkout master'

    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
      displayName: 'Yarn Publish'
      inputs:
        Arguments: release    
#    "release": "yarn lint && yarn test && standard-version && git push --follow-tags && npm publish"
