trigger: none

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  WORKSPACE_DIR: $(Pipeline.Workspace)
  CLI_USER: $(NPM_USER)
  CLI_PASS: $(NPM_PASS)
  CLI_EMAIL: $(NPM_EMAIL)
  NPM_TOKEN: $(NPM_TOKEN)

pool: 'Kube1.15.7'

steps:
- task: Bash@3
  displayName: 'Remove old code'
  inputs:
    targetType: 'inline'
    script: 'rm -rf $(WORKSPACE_DIR)/* && rm -rf $(YARN_CACHE_FOLDER)/'

- checkout: self
  clean: true
  lfs: false
  submodules: false
  persistCredentials: true

- task: Bash@3
  displayName: 'install latest Git'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-add-repository ppa:git-core/ppa -y && sudo apt-get update && sudo apt-get install git -y'

- task: Bash@3
  displayName: 'nvm install'
  inputs:
    targetType: 'inline'
    script: 'sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash'

- task: Bash@3
  displayName: 'Configure nvm'
  inputs:
    targetType: 'inline'
    script: '[ -s /home/AzDevOps/.nvm/nvm.sh ] && \. /home/AzDevOps/.nvm/nvm.sh && [ -s /home/AzDevOps/.nvm/bash_completion ] && \. /home/AzDevOps/.nvm/bash_completion'
  env:
    NVM_DIR: /home/AzDevOps/.nvm

- task: Bash@3
  displayName: 'install node 16.18.0'
  inputs:
    targetType: 'inline'
    script: 'env | sort && sudo nvm install 16.18.0'
  env:
    NVM_DIR: /home/AzDevOps/.nvm

- task: Bash@3
  displayName: 'npm install -g npm-cli-login'
  inputs:
    targetType: 'inline'
    script: 'sudo npm install -g npm-cli-login'

- task: Bash@3
  displayName: 'git switch master'
  inputs:
    targetType: 'inline'
    script: 'git switch master'

- task: Bash@3
  displayName: 'install make'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get update -y && sudo apt-get install -y make && sudo apt install -y g++'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: 'Use Yarn 1.x'

- task: Cache@2
  displayName: 'Yarn Cache'
  inputs:
    key: 'yarn | "$(Agent.OS) | yarn.lock'
    path: $(YARN_CACHE_FOLDER)
    cacheHitVar: 'YARN_CACHE_HIT'
  enabled: true
  
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Install'
  inputs:
    Arguments: install --frozen-lockfile

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Release'
  inputs:
    Arguments: release

- task: Bash@3
  displayName: 'git push'
  inputs:
    targetType: 'inline'
    script: 'git push --follow-tags'

- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useExternalRegistry
    publishEndpoint: 'registry.npmjs.com'