# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'
    exclude:
    - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool: 'Kube1.15.7'

steps:

- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false
  submodules: false
  persistCredentials: true

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: 'Use Yarn 1.x'

- task: Bash@3
  displayName: 'install make'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get update -y && sudo apt-get install -y make && sudo apt install -y g++'

- task: Cache@2
  displayName: 'Yarn Cache'
  inputs:
    key: 'yarn | "$(Agent.OS) | yarn.lock'
    path: $(YARN_CACHE_FOLDER)
    cacheHitVar: 'YARN_CACHE_HIT'
  enabled: true
  
  - task: Bash@3
  displayName: 'npx browserslist@latest --update-db'
  inputs:
    targetType: 'inline'
    script: 'sudo npx browserslist@latest --update-db'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Install'
  inputs:
    Arguments: install --frozen-lockfile --ignore-engines

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn CI'
  inputs:
    Arguments: ci
