trigger: none

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  WORKSPACE_DIR: $(Pipeline.Workspace)
  CLI_USER: $(NPM_USER)
  CLI_PASS: $(NPM_PASS)
  CLI_EMAIL: $(NPM_EMAIL)
  NPM_TOKEN: $(NPM_TOKEN)

pool: 'Kube1.15.7'

steps:
- task: Bash@3
  displayName: 'Remove old code'
  inputs:
    targetType: 'inline'
    script: 'rm -rf $(WORKSPACE_DIR)/* && rm -rf $(YARN_CACHE_FOLDER)/'

- checkout: self
  clean: true
  lfs: false
  submodules: false
  persistCredentials: true

- task: Bash@3
  displayName: 'install latest Git'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-add-repository ppa:git-core/ppa -y && sudo apt-get update && sudo apt-get install git -y'

- task: Bash@3
  displayName: 'npm install -g npm-cli-login'
  inputs:
    targetType: 'inline'
    script: 'sudo npm install -g npm-cli-login && sudo chown -R AzDevOps:AzDevOps ~/.config'

- task: Bash@3
  displayName: 'git switch master'
  inputs:
    targetType: 'inline'
    script: 'git switch master'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: 'Use Yarn 1.x'

- task: Cache@2
  displayName: 'Yarn Cache'
  inputs:
    key: 'yarn | "$(Agent.OS) | yarn.lock'
    path: $(YARN_CACHE_FOLDER)
    cacheHitVar: 'YARN_CACHE_HIT'
  enabled: true
  
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Install'
  inputs:
    Arguments: install --frozen-lockfile

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Release'
  inputs:
    Arguments: release

- task: Bash@3
  displayName: 'login'
  inputs:
    targetType: 'inline'
    script: 'git push --follow-tags && npm publish'
